# Generated by Django 3.2.6 on 2021-10-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(null=True)),
                ('rating', models.IntegerField(max_length=5)),
                ('realese_date', models.DateField()),
            ],
        ),
    ]
