# Generated by Django 3.2.6 on 2021-10-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211028_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='realese_date',
            new_name='release_date',
        ),
    ]
