# Generated by Django 3.2.8 on 2021-11-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20211106_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(to='movies.Director'),
        ),
    ]
